// Generated by tools/gen-theme-diff.py from assets/themes/*.theme.ron.
// Do not edit by hand: run the script when a theme's tokens change.
//
// The Themes scene shows this beside the three buttons, so a visitor can
// see what a theme actually is before pressing anything.
export const THEME_DIFF = {
  "themes": [
    "glass",
    "paper",
    "neon"
  ],
  "rows": [
    {
      "token": "panel role",
      "note": "How the panel is painted at all.",
      "values": [
        "Glass",
        "Tiled",
        "CutCorners"
      ]
    },
    {
      "token": "radii sm/md/lg",
      "note": "The corner scale, in pixels.",
      "values": [
        "8/12/16",
        "2/2/2",
        "0/0/0"
      ]
    },
    {
      "token": "blur",
      "note": "Backdrop blur behind glass. Zero is opaque.",
      "values": [
        "4 px",
        "0 px",
        "0 px"
      ]
    },
    {
      "token": "slot size",
      "note": "One slot's edge. The grid follows it.",
      "values": [
        "44 px",
        "44 px",
        "44 px"
      ]
    },
    {
      "token": "motion scale",
      "note": "The motion scale.",
      "values": [
        "90/180/320 ms",
        "120/160/200 ms",
        "90/140/240 ms"
      ]
    },
    {
      "token": "hover delay",
      "note": "How long a pointer rests before the tooltip.",
      "values": [
        "60 ms",
        "70 ms",
        "50 ms"
      ]
    },
    {
      "token": "body font",
      "note": "Prose and item names.",
      "values": [
        "Manrope",
        "IBM Plex Sans",
        "Manrope"
      ]
    },
    {
      "token": "display font",
      "note": "Counts, labels and numerals.",
      "values": [
        "Barlow Condensed",
        "IBM Plex Mono",
        "Rajdhani"
      ]
    }
  ]
};
