//! Bakes the demo mods and the shared assets into the binary.
//!
//! `examples/modded/mods/` stays the one copy of the three demo mods: this
//! writes a table of `(logical path, include_str!(absolute path))` pairs, so
//! editing a mod on disk rebuilds the playground with the edit and there is
//! never a second copy to drift.
//!
//! The logical paths are the ones `slotted-packs` reads: `mods/<id>/mod.toml`
//! for discovery, `scripts/<id>/<entry>` for the chunks, `data/<id>/...` for
//! RON, and `locale/<id>/<lang>.ftl` for the per-mod form an unlayered source
//! has to use.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets this"));
    let root = manifest.join("../..");
    let mods_dir = root.join("examples/modded/mods");
    let assets = root.join("assets");

    let mut files: Vec<(String, PathBuf)> = Vec::new();

    let mut mod_dirs: Vec<PathBuf> = std::fs::read_dir(&mods_dir)
        .unwrap_or_else(|e| panic!("reading {}: {e}", mods_dir.display()))
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .filter(|path| path.is_dir())
        .collect();
    mod_dirs.sort();

    for dir in &mod_dirs {
        let id = dir
            .file_name()
            .and_then(|name| name.to_str())
            .expect("a mod directory has a utf-8 name")
            .to_owned();
        for (path, relative) in walk(dir) {
            let logical = match relative.split('/').next() {
                // `mod.toml` is discovered under `mods/<id>/`.
                _ if relative == "mod.toml" => format!("mods/{id}/mod.toml"),
                Some("locale") => format!("locale/{id}/{}", &relative["locale/".len()..]),
                Some("data") => format!("data/{id}/{}", &relative["data/".len()..]),
                // Everything else a mod ships is a chunk the loader reads at
                // `scripts/<id>/<entry>`.
                _ => format!("scripts/{id}/{relative}"),
            };
            files.push((logical, path));
        }
    }

    // The base pack: whatever `assets/data/` holds, at the same logical paths
    // the layered source would serve.
    let base_data = assets.join("data");
    if base_data.is_dir() {
        for (path, relative) in walk(&base_data) {
            files.push((format!("data/{relative}"), path));
        }
    }
    let base_locale = assets.join("locale");
    if base_locale.is_dir() {
        for (path, relative) in walk(&base_locale) {
            files.push((format!("locale/{relative}"), path));
        }
    }

    files.sort();
    let mut out = String::from(
        "// Generated by build.rs. Every entry is an `include_str!` of the real\n\
         // file, so the mods under examples/modded/mods stay the one copy.\n\
         /// Logical path to file contents, for the bundled [`InMemorySource`].\n\
         pub const FILES: &[(&str, &str)] = &[\n",
    );
    for (logical, path) in &files {
        println!("cargo:rerun-if-changed={}", path.display());
        let absolute = path.canonicalize().unwrap_or_else(|_| path.clone());
        writeln!(
            out,
            "    ({logical:?}, include_str!({:?})),",
            absolute.to_string_lossy()
        )
        .expect("writing to a String");
    }
    out.push_str("];\n");

    let dest = PathBuf::from(std::env::var("OUT_DIR").expect("cargo sets this")).join("bundle.rs");
    std::fs::write(&dest, out).unwrap_or_else(|e| panic!("writing {}: {e}", dest.display()));
    println!("cargo:rerun-if-changed={}", mods_dir.display());
    println!("cargo:rerun-if-changed=build.rs");
}

/// Every file under `dir`, as `(absolute path, path relative to dir)`.
fn walk(dir: &Path) -> Vec<(PathBuf, String)> {
    fn inner(dir: &Path, prefix: &str, out: &mut Vec<(PathBuf, String)>) {
        let Ok(entries) = std::fs::read_dir(dir) else {
            return;
        };
        let mut paths: Vec<PathBuf> = entries.filter_map(Result::ok).map(|e| e.path()).collect();
        paths.sort();
        for path in paths {
            let Some(name) = path.file_name().and_then(|n| n.to_str()) else {
                continue;
            };
            let relative = if prefix.is_empty() {
                name.to_owned()
            } else {
                format!("{prefix}/{name}")
            };
            if path.is_dir() {
                inner(&path, &relative, out);
            } else {
                out.push((path, relative));
            }
        }
    }
    let mut out = Vec::new();
    inner(dir, "", &mut out);
    out
}
