#!/usr/bin/env python3
"""Turn the three shipped themes into the playground's token diff table.

The showcase contract (docs/design/showcase-contract.md section 3.3) says the
Themes scene's diff panel is static copy generated from the RON files, not
something the wasm module computes. This script is that generation step:

    python3 tools/gen-theme-diff.py

It rewrites examples/web-playground/web/themes.js. Run it when a theme's
tokens change; `just shot-showcase` does not, because the output is checked in.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
THEMES = ["glass", "paper", "neon"]
OUT = ROOT / "examples/web-playground/web/themes.js"

# The slot edge length when a theme names no `sizes` block
# (slotted-theme::tokens::default_slot_size).
DEFAULT_SLOT_SIZE = "44"


def field(text: str, block: str, name: str) -> str | None:
    """`name: <value>` inside the `block: ( ... )` group, as written."""
    at = re.search(rf"\n\s*{block}:\s*\(", text)
    if not at:
        return None
    depth, i = 0, at.end() - 1
    while i < len(text):
        if text[i] == "(":
            depth += 1
        elif text[i] == ")":
            depth -= 1
            if depth == 0:
                break
        i += 1
    inner = text[at.end() : i]
    found = re.search(rf"\b{name}:\s*([^,\n)]+)", inner)
    return found.group(1).strip() if found else None


def num(value: str | None) -> str:
    """`8.0` reads as 8 in a table; the trailing zero is noise."""
    if value is None:
        return "—"
    return value[:-2] if value.endswith(".0") else value


def font(text: str, slot: str) -> str | None:
    found = re.search(rf'"{slot}":\s*\(family:\s*"([^"]+)"', text)
    return found.group(1) if found else None


def panel_kind(text: str) -> str:
    found = re.search(r'\n\s*"panel":\s*(\w+)\(', text)
    return found.group(1) if found else "—"


def read(name: str) -> dict[str, str]:
    text = (ROOT / f"assets/themes/{name}.theme.ron").read_text(encoding="utf-8")
    radii = [num(field(text, "radii", k)) for k in ("sm", "md", "lg")]
    # No spaces around the slashes: the table lives in a 400 px column and
    # every character it does not spend is one the font names get to keep.
    return {
        "panel": panel_kind(text),
        "radii": "/".join(radii),
        "blur": f'{num(field(text, "blur", "radius"))} px',
        "slot": f"{DEFAULT_SLOT_SIZE} px",
        "speed": "/".join(
            num(field(text, "durations", k)) for k in ("fast", "normal", "slow")
        )
        + " ms",
        "hover": f'{num(field(text, "durations", "hover_delay"))} ms',
        "body": font(text, "body") or "—",
        # Every theme names its second face differently; paper's is `mono`.
        "display": font(text, "display") or font(text, "mono") or "—",
    }


ROWS = [
    ("panel", "panel role", "How the panel is painted at all."),
    ("radii", "radii sm/md/lg", "The corner scale, in pixels."),
    ("blur", "blur", "Backdrop blur behind glass. Zero is opaque."),
    ("slot", "slot size", "One slot's edge. The grid follows it."),
    ("speed", "motion scale", "The motion scale."),
    ("hover", "hover delay", "How long a pointer rests before the tooltip."),
    ("body", "body font", "Prose and item names."),
    ("display", "display font", "Counts, labels and numerals."),
]


def main() -> None:
    data = {name: read(name) for name in THEMES}
    rows = [
        {
            "token": label,
            "note": note,
            "values": [data[name][key] for name in THEMES],
        }
        for key, label, note in ROWS
    ]
    body = json.dumps({"themes": THEMES, "rows": rows}, indent=2)
    OUT.write_text(
        "// Generated by tools/gen-theme-diff.py from assets/themes/*.theme.ron.\n"
        "// Do not edit by hand: run the script when a theme's tokens change.\n"
        "//\n"
        "// The Themes scene shows this beside the three buttons, so a visitor can\n"
        "// see what a theme actually is before pressing anything.\n"
        f"export const THEME_DIFF = {body};\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
